name: fdl_demo_app_2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # diagram_editor: ^0.0.10
  diagram_editor:
    path: ../flutter_diagram_editor

  flutter_colorpicker: ^1.0.3
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
